services:
  backend:
    build: .
    container_name: bookstore-backend
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bookstoredb-dev.c1ygoy8q4aqb.ap-southeast-2.rds.amazonaws.com:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: PostgresPassword
      APP_API_URL: http://localhost:8081/api 
      RAZORPAY_KEY_ID: rzp_test_SRtquGCO8OYX1j
      RAZORPAY_KEY_SECRET: gbNHNI2mjEWXqWhhuzf8FVby
    volumes:
      - uploads_data:/uploads
    networks:
      - bookstore-network

networks:
  bookstore-network:
    name: kids-bookstore-network
    driver: bridge

volumes:
  uploads_data:
