package com.bookstore.service;

import com.bookstore.entity.Shop;
import com.bookstore.repository.ShopRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * Manages per-shop frontend containers using docker compose.
 *
 * Strategy:
 * 1. Build the shared base image (kids-bookstore-shop-frontend) once.
 * 2. For each shop, append a new service to docker-compose.shops.yml.
 * 3. Run `docker compose up -d shop-<slug>` so all shops appear in the
 * same compose stack alongside postgres, backend, traefik, etc.
 */
@Service
public class DockerService {

    private static final Logger log = LoggerFactory.getLogger(DockerService.class);
    private static final String SHOP_IMAGE = "kids-bookstore-shop-frontend";
    private static final String NETWORK_NAME = "kids-bookstore_bookstore-network";

    @Value("${app.api.url:http://localhost:8081/api}")
    private String apiUrl;

    /** Path to the mounted frontend source inside the backend container */
    @Value("${app.frontend.source:/app/frontend-src}")
    private String frontendSourcePath;

    /** Path to the main docker-compose.yml (mounted from host) */
    @Value("${app.compose.main:/app/compose/docker-compose.yml}")
    private String mainComposePath;

    /** Path where shops compose file will be written */
    @Value("${app.compose.shops:/app/compose/docker-compose.shops.yml}")
    private String shopsComposePath;

    @Autowired
    private ShopRepository shopRepository;

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    /**
     * Triggered asynchronously after a shop is created.
     * Hardcoded server separated model — No-Op dynamic provisioning.
     */
    @Async
    public void provisionShopContainer(Shop shop) {
        log.info("Provisioning for shop '{}' is handled explicitly via separated Docker compose services.",
                shop.getSlug());
        updateContainerStatus(shop.getId(), "RUNNING", null, null);
    }

    /**
     * Stops and removes a shop's compose service.
     * Hardcoded server separated model — No-Op dynamic stop.
     */
    public void stopShopContainer(Shop shop) {
        log.info("Stopping shop '{}' container is handled manually.", shop.getSlug());
        updateContainerStatus(shop.getId(), "STOPPED", null, null);
    }

    // -------------------------------------------------------------------------
    // Compose file management
    // -------------------------------------------------------------------------

    /**
     * Appends (or replaces) a shop service block in docker-compose.shops.yml.
     * The file is created with a shared header if it doesn't exist yet.
     */
    private synchronized void appendShopService(Shop shop) throws Exception {
        Path composePath = Paths.get(shopsComposePath);

        // Ensure parent directory exists
        Files.createDirectories(composePath.getParent());

        String existingContent = Files.exists(composePath)
                ? Files.readString(composePath)
                : buildComposeHeader();

        // Remove old block for this slug if present, then append fresh block
        String slug = shop.getSlug();
        String serviceBlock = buildServiceBlock(shop);
        String serviceName = composeServiceName(slug);

        // Strip the old service if it exists (between " <name>:" and next service or
        // EOF)
        String stripped = removeServiceBlock(existingContent, serviceName);

        String newContent = stripped.stripTrailing() + "\n\n" + serviceBlock + "\n";
        Files.writeString(composePath, newContent);
        log.info("docker-compose.shops.yml updated for shop '{}'", slug);
    }

    /**
     * Removes a shop's service block from the shops compose file.
     */
    private synchronized void removeShopFromComposeFile(String slug) throws Exception {
        Path composePath = Paths.get(shopsComposePath);
        if (!Files.exists(composePath))
            return;

        String content = Files.readString(composePath);
        String updated = removeServiceBlock(content, composeServiceName(slug));
        Files.writeString(composePath, updated);
    }

    private String buildComposeHeader() {
        return "# Auto-generated by DockerService — do not edit manually\n" +
                "networks:\n" +
                "  bookstore-network:\n" +
                "    external: true\n" +
                "    name: " + NETWORK_NAME + "\n\n" +
                "services:\n";
    }

    private String buildServiceBlock(Shop shop) {
        String slug = shop.getSlug();
        String serviceName = composeServiceName(slug);
        String primaryColor = shop.getPrimaryColor() != null ? shop.getPrimaryColor() : "#3f51b5";
        String logoUrl = shop.getLogoUrl() != null ? shop.getLogoUrl() : "";
        String shopName = shop.getName().replace("\"", "\\\"");

        return "  " + serviceName + ":\n" +
                "    image: " + SHOP_IMAGE + "\n" +
                "    container_name: " + serviceName + "\n" +
                "    restart: unless-stopped\n" +
                "    environment:\n" +
                "      SHOP_SLUG: \"" + slug + "\"\n" +
                "      SHOP_NAME: \"" + shopName + "\"\n" +
                "      PRIMARY_COLOR: \"" + primaryColor + "\"\n" +
                "      LOGO_URL: \"" + logoUrl + "\"\n" +
                "      API_URL: \"" + apiUrl + "\"\n" +
                "    networks:\n" +
                "      - bookstore-network\n" +
                "    labels:\n" +
                "      - \"traefik.enable=true\"\n" +
                "      - \"traefik.http.routers." + slug + ".rule=Host(`" + slug + ".localhost`)\"\n" +
                "      - \"traefik.http.routers." + slug + ".entrypoints=web\"\n" +
                "      - \"traefik.http.services." + slug + ".loadbalancer.server.port=80\"\n";
    }

    /**
     * Removes a named service block from compose YAML content.
     * Strips from " <serviceName>:\n" to the next top-level service or EOF.
     */
    private String removeServiceBlock(String content, String serviceName) {
        String marker = "  " + serviceName + ":";
        int start = content.indexOf("\n" + marker);
        if (start == -1)
            start = content.indexOf(marker); // first service
        if (start == -1)
            return content;

        // Find where next sibling service starts (two-space indented at same level)
        int nextService = content.indexOf("\n  ", start + marker.length());
        // Walk forward to find a line that is a service (not deeper indented)
        while (nextService != -1) {
            int lineEnd = content.indexOf('\n', nextService + 1);
            String line = lineEnd == -1
                    ? content.substring(nextService + 1)
                    : content.substring(nextService + 1, lineEnd);
            // A sibling service starts with exactly two spaces then non-space
            if (line.startsWith("  ") && !line.startsWith("   "))
                break;
            nextService = content.indexOf("\n  ", nextService + 1);
        }

        if (nextService == -1) {
            // This was the last service
            return content.substring(0, start).stripTrailing() + "\n";
        } else {
            return content.substring(0, start) + "\n" + content.substring(nextService + 1);
        }
    }

    // -------------------------------------------------------------------------
    // Docker / Compose commands
    // -------------------------------------------------------------------------

    /**
     * Builds the base shop frontend image if it doesn't already exist.
     */
    private void ensureShopImageBuilt() throws Exception {
        int checkExit = runCommand(List.of("docker", "image", "inspect", SHOP_IMAGE), false);
        if (checkExit == 0) {
            log.info("Shop frontend image already exists, skipping build.");
            return;
        }
        log.info("Building shop frontend image from {} ...", frontendSourcePath);
        int exit = runCommand(List.of(
                "docker", "build",
                "-f", frontendSourcePath + "/Dockerfile.shop",
                "--build-arg", "VITE_API_URL=" + apiUrl,
                "-t", SHOP_IMAGE,
                frontendSourcePath), true);
        if (exit != 0)
            throw new RuntimeException("Docker image build failed (exit=" + exit + ")");
        log.info("Shop frontend image built.");
    }

    /**
     * Runs `docker compose -f main -f shops up -d <serviceName>`.
     */
    private void startComposeService(String serviceName) throws Exception {
        int exit = runCommand(List.of(
                "docker", "compose",
                "-p", "kids-bookstore",
                "-f", mainComposePath,
                "-f", shopsComposePath,
                "up", "-d", serviceName), true);
        if (exit != 0)
            throw new RuntimeException("docker compose up failed for service: " + serviceName);
    }

    private int runCommand(List<String> cmd, boolean logOutput) throws Exception {
        log.debug("Running: {}", String.join(" ", cmd));
        ProcessBuilder pb = new ProcessBuilder(cmd).redirectErrorStream(true);
        Process proc = pb.start();
        if (logOutput) {
            try (BufferedReader reader = new BufferedReader(
                    new InputStreamReader(proc.getInputStream()))) {
                String line;
                while ((line = reader.readLine()) != null)
                    log.info("[docker] {}", line);
            }
        } else {
            proc.getInputStream().transferTo(java.io.OutputStream.nullOutputStream());
        }
        proc.waitFor(300, TimeUnit.SECONDS);
        return proc.exitValue();
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private String composeServiceName(String slug) {
        return "shop-" + slug;
    }

    private void updateContainerStatus(Long shopId, String status, String containerId, Integer port) {
        shopRepository.findById(shopId).ifPresent(s -> {
            s.setContainerStatus(status);
            if (containerId != null)
                s.setContainerId(containerId);
            if (port != null)
                s.setContainerPort(port);
            shopRepository.save(s);
        });
    }
}
