spring.application.name=backend

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/bookstore_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Error handling
server.error.include-message=always

# File Upload
app.upload.dir=/uploads

# Security (JWT) - valid for 24 hours
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000
# Google OAuth
bookstore.google.clientId=73164381864-2lja69ojtmf6liobjr5cn6rdc6s3kmtn.apps.googleusercontent.com

# Docker / Compose integration
app.api.url=${APP_API_URL:http://localhost:8081/api}
# The public URL of the backend API (use your ngrok URL or real domain here)
app.public.url=${APP_PUBLIC_URL:http://ec2-13-239-122-152.ap-southeast-2.compute.amazonaws.com:8081/api}
app.frontend.source=${APP_FRONTEND_SOURCE:/app/frontend-src}
app.compose.main=${APP_COMPOSE_MAIN:/app/compose/docker-compose.yml}
app.compose.shops=${APP_COMPOSE_SHOPS:/app/compose/docker-compose.shops.yml}

# logging.level.org.springframework.web.cors=DEBUG
# logging.level.org.springframework.security.web.cors=DEBUG
logging.level.com.bookstore=INFO

# AWS S3 Integration
aws.s3.bucket-name=${AWS_S3_BUCKET:}
aws.access-key=${AWS_ACCESS_KEY_ID:}
aws.secret-key=${AWS_SECRET_ACCESS_KEY:}
aws.region=${AWS_REGION:us-east-1}

# Razorpay Configuration
razorpay.key_id=${RAZORPAY_KEY_ID}
razorpay.key_secret=${RAZORPAY_KEY_SECRET}
logging.level.org.springframework.web=DEBUG
logging.level.com.bookstore=DEBUG
spring.mvc.log-request-details=true
server.error.include-message=always
logging.level.org.springframework.security=DEBUG

# Mail Configuration (AWS SES)
spring.mail.host=${SPRING_MAIL_HOST:email-smtp.ap-southeast-2.amazonaws.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SES_USERNAME}
spring.mail.password=${SES_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=${SPRING_MAIL_FROM:noreply@bookstore.com}

# Instagram / Meta API
instagram.app.id=${INSTAGRAM_APP_ID:}
instagram.app.secret=${INSTAGRAM_APP_SECRET:}
instagram.redirect.uri=${INSTAGRAM_REDIRECT_URI:http://localhost:5176/instagram/callback}
